/// Generic
const MARGIN_SMALL = 4.0;
const MARGIN_MEDIUM = 8.0;
const MARGIN_MEDIUM_2X = 16.0;
const MARGIN_MEDIUM_3X = 24.0;

const MARGIN_LARGE = 32.0;
const MARGIN_XLARGE = 40.0;
const MARGIN_XXLARGE = 48.0;

const TEXT_HEADER_1X = 24.0;
const TEXT_HEADER_2X = 32.0;
const TEXT_HEADER_3X = 40.0;

const TEXT_REGULAR_1X = 14.0;
const TEXT_REGULAR_2X = 16.0;
const TEXT_REGULAR_3X = 18.0;

/// App Specific
const ADD_ITEM_PAGE_CATEGORY_CARD_HEIGHT  = 200.0;
const ADD_ITEM_PAGE_NOTE_CARD_HEIGHT = 260.0;
const ADD_ITEM_PAGE_SLIDER_CARD_HEIGHT = 100.0;
const ADD_ITEM_PAGE_PRICE_CARD_HEIGHT = 130.0;
const DIM_BUTTON_HEIGHT = 50.0;

const RENT_ITEM_VIEW_HEIGHT = 100.0;

const ITEM_DETAILS_PAGE_PRICE_CARD_HEIGHT = 150.0;
const CATEGORY_VIEW_HEIGHT = 60.0;
